version: "3.7"

services:
  loki:
    image: slimbean/loki-live:arm64-2022-02-21-33262255
    command: "-config.file=/etc/loki/loki-config.yaml -log.level=info"
    restart: always
    network_mode: "host"
    volumes:
      - "/srv/loki:/var/lib/loki"
      - "/home/pi/loki/loki.yaml:/etc/loki/loki-config.yaml"
  grafana:
    image: slimbean/grafana-arm64-82dc1971
    user: "1000"
    restart: always
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_FEATURE_TOGGLES_ENABLE=fullRangeLogsVolume lokiLive
    network_mode: "host"
    volumes:
      - "/home/pi/grafana:/var/lib/grafana"
  minio:
    image: minio/minio:RELEASE.2022-02-12T00-51-25Z
    command: server --console-address ":9001" /data
    network_mode: "host"
    volumes:
      - "/srv/minio:/data"
#  promtail:
#    image: ""
#    command: -config.file=/etc/promtail/config.yaml
#    network_mode: "host"
#    volumes:
#      - "/home/pi/promtail/promtail-config.yaml:/etc/promtail/config.yaml"





#  leafbus:
#    image: "slimbean/leafbus:latest"
#    #restart: "always"
#    network_mode: "host"
